version: '2'
services:
  #data container
  data:
    image: debian:jessie

  #webserver container
  expressjs:
    build: expressjs
    volumes_from:
      - data:rw
    depends_on:
      - mongodb
    ports:
      - "3000"

  #mongodb container
  mongodb:
    image: mongo:3.4

  # bower updater
  bower_updater:
    build: bower_updater
    volumes_from:
      - data:rw

  # Nginx Web Proxy.
  nginx:
    build: nginx
    depends_on:
      - expressjs
    volumes_from:
      - data:ro