version: '2'
services:
  #data container
  data:
    volumes:
      - /share/manacheck:/var/www/manacheck

  # bower updater
  bower_updater:
    command: ["bin/bash","-c", "cd /var/www/manacheck/frontend \
    && grunt build"]

  # Nginx Web Proxy.
  nginx:
    ports:
      - "8080:80"