version: '2'
services:
  #data container
  data:
    image: debian:jessie
    volumes:
      - ../:/var/www/manacheck

  # bower updater
  bower_updater:
    command: ["bin/bash","-c", "cd /var/www/manacheck/frontend \
    && npm install \
    && node_modules/bower/bin/bower install --allow-root \
    && grunt build-dist"]

  # nginx
  nginx:
    ports:
      - "80:80"
  
  #mongodb container
  # on production should use host system folder
  mongodb:
    image: mongo:3.4
    volumes:
      - ../mnt:/data/db

  # express js
  expressjs:
    command: ["bin/bash","-c", "cd /var/www/manacheck/backend && npm install && node bin/www"]